# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-08 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.IntegerField(db_column='Fld', primary_key=True, serialize=False)),
                ('assets_id', models.CharField(default=None, max_length=255)),
                ('assets_name', models.CharField(default=None, max_length=255)),
                ('assets_brand', models.CharField(default=None, max_length=255)),
                ('assets_version', models.CharField(default=None, max_length=255)),
                ('assets_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('buying_date', models.DateField(default=None)),
                ('notes', models.CharField(default=None, max_length=1024)),
            ],
        ),
    ]
