# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180408_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_detial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assets_id', models.CharField(default=None, max_length=255)),
                ('create_date', models.DateField(default=None)),
                ('create_type', models.CharField(default=None, max_length=255)),
                ('use_department', models.CharField(default=None, max_length=255)),
                ('use_people', models.CharField(default=None, max_length=255)),
                ('asset_status', models.IntegerField(default=0, max_length=2)),
            ],
        ),
    ]
