# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_asset_detial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_detial',
            name='asset_status',
            field=models.IntegerField(default=0),
        ),
    ]
