# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-10 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180409_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_detial',
            name='asset_status',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_status',
            field=models.IntegerField(default=0),
        ),
    ]
