# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180410_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='buying_date',
            field=models.DateField(default='1997-01-01'),
        ),
    ]
