# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_detial',
            name='use_department',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
